### ISSUE TITLE
mno01: weirrd ipv4 setup

### ISSUE THREAD

**Issue by liske** [dd-ix/nix-config#45]
We accidentally used the network base for the gateway :facepalm: 

https://github.com/dd-ix/nix-config/blob/0159100fab79ec464b55a71aba48caddba89f1af/hosts/mno001/network.nix#L69

The gateway has been fixed and mno01 has been monkey patched with `s/.177/.176/`.

**Comment by tanneberger** [comment]
why not make a PR ;D @liske
