### ISSUE TITLE
Alice LG: add missing `rejection_reasons`

### ISSUE THREAD

**Issue by liske** [dd-ix/nix-config#83]
We need a `[rejection_reasons]` section for the communities that are used to indicate reject causes on our route servers. Currently error cause communities are not highlighted at all.

**Comment by MarcelCoding** [comment]
I think we would need to classify all communities in which category they belong?

**Comment by icebreak24** [comment]
The variable name is simply wrong in the alice-lg.nix file. ;)

Wrong
`reject_reasons = {
            "57328:1101:3" = "Prefix is bogon";
            "57328:1101:4" = "Invalid ASN in AS_PATH";
            "57328:1101:5" = "Invalid AS_PATH length";
            "57328:1101:7" = "Invalid left-most ASN";
            "57328:1101:8" = "Invalid NEXT_HOP";
            "57328:1101:9" = "Prefix not in IRRDB AS-SETs";
            "57328:1101:10" = "Origin ASN not in IRRDB AS-SETs";
            "57328:1101:13" = "RPKI INVALID route";
            "57328:1101:14" = "Transit-free ASN in AS_PATH";
          };`

Right
`rejection_reasons = {
            "57328:1101:3" = "Prefix is bogon";
            "57328:1101:4" = "Invalid ASN in AS_PATH";
            "57328:1101:5" = "Invalid AS_PATH length";
            "57328:1101:7" = "Invalid left-most ASN";
            "57328:1101:8" = "Invalid NEXT_HOP";
            "57328:1101:9" = "Prefix not in IRRDB AS-SETs";
            "57328:1101:10" = "Origin ASN not in IRRDB AS-SETs";
            "57328:1101:13" = "RPKI INVALID route";
            "57328:1101:14" = "Transit-free ASN in AS_PATH";
          };`

**Comment by MarcelCoding** [comment]
thx for the hint, I've fixed the typo
